name: Deploy Docker Image

on:
  workflow_dispatch:   # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # -------------------------
      # LOGIN TO ECR
      # -------------------------

      - name: Login to Amazon ECR
        run: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com


      # -------------------------
      # BUILD DOCKER IMAGE
      # -------------------------

      - name: Build Docker image
        run: docker build -t cats-dogs-app .

      # -------------------------
      # TAG IMAGE
      # -------------------------

      - name: Tag Docker image
        run: |
          docker tag cats-dogs-app:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/catsanddogs:latest

      # -------------------------
      # PUSH IMAGE
      # -------------------------

      - name: Push Docker image
        run: |
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/catsanddogs:latest

# trigger

